services:
  postgres:
    image: postgres:16
    container_name: smartrent-db
    environment:
      POSTGRES_DB: smartrent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"